
sude: required 
language: generic 

services:
  - docker 

before_install:
  - docker build -t taro/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true taro/docker-react npm run test
