
sude: required 
language: generic 

services:
  - docker 

before_install:
  - docker build -t taro/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true taro/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker" 
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-251387535001" 
  bucket_path: "docker" 
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

